### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Sergio-Ka** [mmmnumber37/task2_uikit#1]
1. надо переписать весь код на классы js. Это необходимо здесь в целях инкапсуляции состояния. По БЭМ нельзя использовать id, а если делать селекцию по классу в DOM, то при одинаковых классах (например несколько слайдеров на странице) настройки одного слайдера будут применятся ко всем. Если же для каждого слайдера создавать инстанс и в него передавать разные настройки, то таких проблем можно будет избежать. Использовать классы ES6. При сдаче все равно нужно будет выучить, что это синтаксический сахар, но пока пользовать их, потому что они визуально легко воспринимаются да и вообще много где пользуются. Вот код для примера:
```
class SliderWithPopUp {

  constructor($element) {
    this.$element = $element;
    this.initSlider();
  }

  getSliderSettings() {
    const value = this.$element.data('value');

    return {
      min: this.$element.data('min'),
      max: this.$element.data('max'),
      step: this.$element.data('step'),
      value: value,
      range: this.$element.data('range'),
      create: (event) => {
        const $sliderHandle = $(event.target).find('.ui-slider-handle');
        $sliderHandle.append(`<input class="slider-with-pop-up__value js-slider-with-pop-up__value" value="${value}"/><div class="slider-with-pop-up__value-tail"></div>`);
      },
      slide: (event, ui) => {
        const $sliderValue = $(event.target).find('.js-slider-with-pop-up__value');
        $sliderValue.val(ui.value);
      },
    }
  }

  initSlider() {
    this.$element.slider(this.getSliderSettings());

    const $sliderTheme = this.$element.data('theme');
    const $sliderHandle = this.$element.find('.ui-slider-handle');
    const $sliderMinRange = this.$element.find('.ui-slider-range-min');

    $sliderHandle.addClass(`slider-with-pop-up__handle_theme_${$sliderTheme}`);
    $sliderMinRange.addClass(`slider-with-pop-up__range-min_theme_${$sliderTheme}`);
  }
}

$('.js-slider-with-pop-up').each((index, domElement) => {
  new SliderWithPopUp($(domElement));
});


mixin slider-with-pop-up(options = {min: 0, max: 100, step: 1, value: 40, range: "", theme: "orange"})
    -let {min = 0, max = 100, step = 1, value = 40, range = "", theme = "orange"} = options;
    .slider-with-pop-up.js-slider-with-pop-up(data-min= min, data-max= max, data-step= step, data-value= value, data-range= range, data-theme= theme)
```

2. Про такую ерунду уже писал вроде бы, про var, про ++, надо поглядеть в о всем проекте
```
for(var n = 0; n < count; n++)
```

**Comment by mmmnumber37** [comment]
Google Map тоже переписывать? И возможно реализовать множественное добавление?

**Comment by Sergio-Ka** [comment]
Гуглокарту тоже переписывать. А в чем разница? Смысл классов в инкапсуляции сложности и состояния, и для этого это делается, а не для того чтобы тупо код переписывать ради переписывания. В целом посмотрел, не плохо на мой взгляд. Пара замечаний такие:
1. Везде БЭМ страдает. Ты везде добавляешь элементы динамически с префиксом js- и внутри них БЭМ не видно. Одно другому мешать не должно. Представь вначале статичную структуру тэгов без JS, отименуй их как надо по БЭМ и уже потом js добавляй. Эти элементы с префиксами кстати вешаются только чтобы к элементам обращаться из js, на них стилей никаких быть не должно. Если тебе понадобится с того или иного элемента убрать взаимодействие с js, ты просто убираешь класс с префиксом, но внешний вид не страдает, так как стили на них никакие не висят, как я уже сказал. И по имени эти классы с префиксом js должны повторять основной класс элемента.
2. В стандартах есть требование на тему того, что конструктор класса должен быть максимально легковесным, то есть вот здесь например:
```
class CalendarApp {
  constructor($element) {
    this.$calendar = $element;
    this.date = new Date();
    this.days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    this.months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];

    this.initCalendarApp();
  }
```
у тебя много лишнего. Вынеси все эти константы в отдельный метод, который будешь вызывать в this.initCalendarApp, у тебя должно остаться примерно так:
```
class CalendarApp {
  constructor($element) {
    this.$calendar = $element;
    this.initCalendarApp();
  }
Посмотри это везде.

**Comment by Sergio-Ka** [comment]
Кстати еще одно замечание. Приватные методы классов должны именоваться начиная со знака нижнего пробела "_".

**Comment by Sergio-Ka** [comment]
Везде одна и та же проблема 'calendar__today js-calendar-today' - это например элемент - а второй класс с префиксом не по БЭМ. То есть надо сделать название с префиксом как основное название + префикс: 'calendar__today js-calendar__today'. Это во всех js у тебя.
