### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [mmmnumber37/task2_uikit#2]
1. давай на этом и последующих проектах будем использовать нотацию БЭМ которая используется в FSD, а именно с нижними подчеркиваниями вместо такого `button--size-small`
2. Я так понимаю запись такого рода означает использование миксов? Миксы в БЭМ запрещены. И такого много по проекту.
```
.slider {
  width: 16.25rem;
  height: 0.3125rem;
  border: none;
  box-shadow: none;
  font-family: $Lato;

  .noUi-base {
    background: #e5e5e5;
    border-radius: 1.25rem;
  }
```
3. Про именование с использованием цифр говорил кажется, что это плохая практика `slider-1`там еще видел какие-то такие примеры. Именование любых сущностей с использованием цифр это всегда плохо.
4. id в бэм не используются, селекторы по классу. Как отличать по одинаковому классу я написал уже в другом issue

**Comment by mmmnumber37** [comment]
Я правильно понимаю, говорится про миксы SASS? А на указанном куске кода, я хотел явно указать на элементы DOM которые создает сторонний плагин.

**Comment by Sergio-Ka** [comment]
Миксы и миксины - вещи разные. Когда про миксы - речь в контексте БЭМ, когда в атрибуте class какого-либо тега указываются 2 или более классов. Я перепоутал, написал не правильно, не микс а каскад. Эта запись похожа на каскад. То есть ты описываешь правило css что если есть элемент с классом .slider, и в нем есть элемент с классом .noUi-base, то тогда использовать описанные в .noUi-base  стили. Каскады нельзя по БЭМ использовать, это повышает специфичность. Если это сторонний плагин - то лучше наверное в корне проекта в папке vendors поместить эти стили в каком-то отдельном файле.

**Comment by Sergio-Ka** [comment]
Чего-то я смотрю и с именованием в соотвествии с БЭМ дела вообще не очень как-то обстоят, что странно. На первом проекте вроде нормально было все. Рассмотрим пример:
```
    case theme
        when "green"
            - classTheme = "arrow_color-green" 
        when "green-inversion"
            - classTheme = "arrow_color-green-inversion"
        when "grey"
            - classTheme = "arrow_color-grey"
        default
            - classTheme = ""

    button.arrow(class=classTheme)
            case sign
                when 'right'
                    i.arrow__img.arrow_right
                when 'left'
                    i.arrow__img.arrow_left

```
1. в частности вот это arrow_color-green
модификаторы ключ-значение пишутся в этой нотации через нижний пробел, то есть так arrow_color_green, arrow_color_green-inversion, arrow_color_grey. И вообще все такого рода модификаторы пишутся так, например button_size_small и так далее. То есть size, color тут ключи, а значения ключей скажем green и small пишутся через нижний пробел всегда.
2. Модификаторы в принципе бывают двух видов - это ключ-значение и булевы. Про ключ значение сказал, про булевы - это которые либо есть либо нет. И когда именование вот такое arrow_right это выглядит странно. Типа переводится стрелка-право? Что право? Есть или нет право? Вот если бы это был модификатор arrow_direction_right, то это бы звучало и выглядело логично, хотя это был бы уже не булевый модификатор а модификатор ключ _значение. Булевый используют, когда важно только наличие или отсутствие модификатора, а его значение несущественно. Например, «отключен»: disabled, button_disabled. Считается, что при наличии булевого модификатора у сущности его значение равно true.
3. Вот здесь arrow__img.arrow_right Тоже плохо. Модификатор который на сущность вешается должен быть ее модификатором, а здесь сущность - это элемент img БЭМ-блока arrow, а на него почему-то вешается модификатор самого блока, а так нельзя. Тут должно быть что-то типа arrow__img.arrow__img_direction_right
И так примерно по всем блокам. Вообще все эти ошибки слишком типовые когда человек БЭМ не понимает. Советую еще раз изучить https://ru.bem.info/ и в частности https://ru.bem.info/methodology/quick-start/. Это важно ибо методология реально крутая и действенная, и кроме того у нас только она и используется.
